### ISSUE TITLE
queue id not recognized in lagopus 0.2.10

### ISSUE THREAD

**Issue by ThomasDeiss** [lagopus/lagopus#101]
I've tried to use queues with lagopus 0.2.10, but already the configuration file does not parse. Lagopus complains about -id being a bad option
"data":"Bad opt = -id.", "line": 7,
This is actually the outcome when trying to parse integration_test/tools/test_scenarios_yaml/ofp/ofp_queue.dsl

Removing the -id parameter helps to get the configuration file parsed, but then I don't know how to access the queue in a set-queue command.

Any help would be appreciated.

**Comment by hibitomo** [comment]
Hi @ThomasDeiss,

Queue Id is set by port configuration of the DSL.
Would you see the commit and the diff?
https://github.com/lagopus/lagopus/commit/7edc94c08d21f10bfd3bbdd2ac4dc5c3f7c6a8e8#diff-0ea4a2272d48fd4ce3777f6491768dd7

Thanks.

**Comment by ThomasDeiss** [comment]
Thanks for the hint
removing the -id parameter from the queue command and using instead
port port05 create -interface interface05 -queue queue032 32 -queue queue039 39
solved the issue.
