### ISSUE TITLE
Using with Ryu guide

### ISSUE THREAD

**Issue by pjpradeepjha** [lagopus/lagopus#119]
I am using the Lagopus book guide to using the lagopus switch with Ryu controller. I am following the step by step guide as provided in this link
[sample ryu software switch](http://www.lagopus.org/lagopus-book/en/html/sample-ryu-simplesw.html)

What I do not understand is, we have ports on the switch VM and we have namespace hosts on the client VM. But how did the host connect to the ports from one VM to another?

**Comment by ebiken** [comment]
Any hypervisor (VirtualBox, VMware, MS Hyper-V etc.) has a way to connect ports among VMs. So follow document of the hypervisor you are using.

If you are using KVM, then below page could help.
Simply connect ports of VMs via bridge on the host.
http://www.lagopus.org/lagopus-book/en/html/installation-kvm.html
After that, you can assign ports to namespaces.

**Comment by pjpradeepjha** [comment]
Hi @ebiken 

thanks for the reply. I am using Oracle VirtualBox. I have setup 1 VM with Lagopus Raw Socket switch with 2 extra interfaces enp0s8 and enp0s9 which I am using as ports. On the other VM, I have created 2 namespace host1 (enp0s8, 10.0.0.1) and host2 (enp0s9, 10.0.0.2).

As per the guide I mentioned above everything goes correctly till 

```
connected socket:<eventlet.greenio.base.GreenSocket object at 0x7f1de23b61d0> address:('127.0.0.1', 49928)
hello ev <ryu.controller.ofp_event.EventOFPHello object at 0x7f1de23b6810>
move onto config mode
EVENT ofp_event->SimpleSwitch13 EventOFPSwitchFeatures
switch features ev version=0x4,msg_type=0x6,msg_len=0x20,xid=0xc28ef426,OFPSwitchFeatures(auxiliary_id=0,capabilities=79,datapath_id=1,n_buffers=65535,n_tables=255)
move onto main mode
```

But then the hosts cannot ping each other, which I believe is obvious as I believe that the host1 and host2 on client VM are not connected with the port1 and port2 on switch vm. 
Is there a guide to connect the hosts in one vm to the interfaces in another vm FOR ORACLE VIRTUALBOX?

Thanks again in advance!

**Comment by pjpradeepjha** [comment]
Great. in VirtualBox with Internal Networking adapters, all we need is to have the same interface name like intnet01 on both the VM. i.e. If we are running 2 guest VMs on the same host, internal networking ports with the same name will automatically be linked together by VBox. 

The hosts can now ping each other with Ryu controller on the switch VM. Gonna try the same with ONOS controller now.

Thanks. @ebiken @kishiguro  @falcon8823
