### ISSUE TITLE
Support for ARM 32 bit

### ISSUE THREAD

**Issue by kapiladhikesavalu** [lagopus/lagopus#141]
## Summary

Does Lagopus support ARM 32 bit ? If so, can it support both raw socket and DPDK ?

**Comment by iMasaruOki** [comment]
So far, raw socket only supports, I think.  Lagopus with DPDK needs PMD support, but ARM 32bit SoCs has too much variant NICs.

**Comment by kapiladhikesavalu** [comment]
Great thanks.
