### ISSUE TITLE
Bad I/O performance using librte_pmd_pcap on Veth ports.

### ISSUE THREAD

**Issue by bfarooq786** [lagopus/lagopus#153]
Issue:  Bad I/O performance using librte_pmd_pcap on Veth ports.
 
Summary:
 
    The DSL file :  

       interface interface0 create -type ethernet-dpdk-phy -device "net_pcap0,iface=veth0"
       interface interface0 create -type ethernet-dpdk-phy -device "net_pcap0,iface=veth5"

   Lagopus Cmd: 

     lagopus -C /usr/share/doc/lagopus/examples/lagopus.dsl -l /var/log/a.log -- -c7 -n1 -- -- rx"(0,0,2)" -- tx"(0,3)" -- rx"(1,0,2)" -- tx"(1,3)" -w3 --core-assign balance 

     Using 3 logical cores & 3 worker threads & only single Queue & 1024 tx & rx descriptors.

   Traffic is sent bidirectional between veth0 & veth5 and calculated the performance.
On X86 ATOM family processor getting around 100 Mbps only (IMIX traffic.)
Increasing the cores from 2 to 3 or 4 does not increase the throughput. 
Did I miss any thing ? Appreciate if folks who are using pcap PMD can throw some light.
 Also noticed for 2 cores , only 1 cores is showing as 100% (In Linux TOP command) utilization and with 3 cores
only 2 cores are showing as 100%. 
The thread that showing 100% is lcore-slave.

Expected :   1 Gbps Through put.

**Comment by hibitomo** [comment]
pcap pmd is a very low performance PMD.
It is difficult to improve the performance.

Could you use Vhost PMD (for virtual machines)?

If you connect Lagopus to dpdk-enabled NFV containers, you can use Virtio-user.
http://doc.dpdk.org/guides/howto/virtio_user_for_container_networking.html

**Comment by bfarooq786** [comment]
Thanks.

    I am using Lagopus as an DPDK application running on Linux OS.

 My requirement is 

  I/O port --- My Application Running in Kernel ----- Lagopus ---- My Application Running in Kernel ----I/O port.

 Here I am using the VETH ports from my application to Lagopus and enabled the PCAP pmd on lagopus.

I don't have an option to use Virtio or Vhost because my application is not running in user space.
Is there a way through which I can do Zero Copy for I/O packets from Kernal to userspace application like Lagopus. Did Lagopus provide a way to get the packets from Kernal to Userspace other than DPDK binded nics.

**Comment by hibitomo** [comment]
DPDK has Kernel module interface(KNI).
Unfortunately, however, Lagopus does not support KNI.

Is it possible for you to separate your application to VM?
If following the architecture below, Lagopus and your application can send and receive with one copy.

``` 
    +----------------------------------------------------+
    |                                                    |
    | +------------------------------------------------+ |
    | |                                                | |
    | |         Your Kernel Application on VM          | |
    | |                                                | |
    | +------------------------------------------------+ |
    |          |       |               |      |          |
    |          |       | Vhost   Vhost |      |          |
    |          |       | PMD     PMD   |      |          |
    | PCI Path |    +--------------------+    | PCI Path |
    | Through  |    |                    |    | Through  |
    |          |    |  Lagopus vSwitch   |    |          |
    |          |    |                    |    |          |
    |          |    +--------------------+    |          |
    |       +-----+                        +-----+       |
    |       | NIC |                        | NIC |       |
    +----------------------------------------------------+
```

**Comment by bfarooq786** [comment]
Thanks.

   with this design there will be dependency on host Os.

Our requirement is to run application along with lagopus switch inside vm.
