### ISSUE TITLE
PacketOut: packet malformed when plengh < 60 (v0.2.1)

### ISSUE THREAD

**Issue by ebiken** [lagopus/lagopus#55]
Since v0.2.1, Lagopus started to send malformed packet when packet length in PacketOut is less than 60. (malformed = initial 10~20 bytes of the packet will be 0x00)

Seems like change in rawsock_send_packet_physical() caused this issue.
I have confirmed correct packet will be sent out after below change to v0.2.1 code.
```c
- memset(OS_M_APPEND(m, 60 - plen), 0, (uint32_t)(60 - plen));
+ memset(OS_M_APPEND(m, 60 - plen) + plen, 0, (uint32_t)(60 - plen));
```
However, I was not sure if this is correct fix or I should change OS_M_APPEND macro.
So would appreciate if you can clarify intent of the macro and correct (clean) way to fix this.

## FYI: changes beween 0.2.1 / 0.2.0.
* src/dataplane/sock/sock.c:
```c
# Lagopus 0.2.1
rawsock_send_packet_physical(struct lagopus_packet *pkt, uint32_t portid) {
  if (pollfd[portid].fd != 0) {
    OS_MBUF *m;
    uint32_t plen;

    m = pkt->mbuf;
    plen = OS_M_PKTLEN(m);
    if (plen < 60) {
      memset(OS_M_APPEND(m, 60 - plen), 0, (uint32_t)(60 - plen));
    }
    (void)write(pollfd[portid].fd, pkt->mbuf->data, OS_M_PKTLEN(pkt->mbuf));
  }
  lagopus_packet_free(pkt);
  return 0;
}
# Lagopus 0.2.0
rawsock_send_packet_physical(struct lagopus_packet *pkt, uint32_t portid) {
  if (pollfd[portid].fd != 0) {
    (void)write(pollfd[portid].fd, pkt->mbuf->data, OS_M_PKTLEN(pkt->mbuf));
  }
  lagopus_packet_free(pkt);
  return 0;
}
```

**Comment by ynkjm** [comment]
Thank you for a bug report.

So we have fixed this bug at this commit.
https://github.com/lagopus/lagopus/commit/289df06508471f448cfeb82f66245ef173d1691c

We will release 0.2.2 that contains this commit.

Thanks!

**Comment by ebiken** [comment]
Thanks. Confirmed v0.2.1 + above commit fixed the issue I've reported.
