### ISSUE TITLE
crashing when flows have specified in the dsl file (w/ DPDK).

### ISSUE THREAD

**Issue by ashalimov** [lagopus/lagopus#58]
On Lagopus 0.2 and DPDK with the following dsl file, the switch crashes with segfault.

> interface interface01 create -type ethernet-dpdk-phy -port-number 0
> interface interface02 create -type ethernet-dpdk-phy -port-number 1
> port port01 create -interface interface01
> port port02 create -interface interface02
> bridge bridge01 create -port port01 1 -port port02 2 -dpid 0x1
> bridge bridge01 enable
> flow bridge01 add in_port=1 apply_actions=output:2

This happens in **clear_worker_flowcache()** at line **clear_all_cache(lp->cache)**; because at that time **lp->cache** is _NULL_.

Currently, I could not find the quick fix for that.  It looks this is __an architectural issues__. Below is an explanation.

DPDK-based flow cache initialization happens during **dataplane_start()**. But adding the flow eventually accesses flow_cache via **datastore_init()** that runs BEFORE dataplane.

Here is the trace:
 * main() -> lagopus_mainloop() -> s_do_mainloop() -> s_prologue()
 * In prologue, lagopus_module_init_all() -> **datastore_init()** -> add_sub_cmd_parse() -> flow_cmd_mod_add_cmd_parse() -> ofp_flow_mod_check_add() -> **clear_flowcache()**
 * In prologue, lagopus_module_start_all() -> **dataplane_start()** -> app_lcore_main_loop() -> app_lcore_main_loop_worker() -> **init_flowcache()**

**Comment by ynkjm** [comment]
Hi,

Thank you for a bug report.

The following patch will solve this bug. 
Would you check it on your environment?

```C
 src/dataplane/ofproto/ofcache.c | 4 ++++
 1 file changed, 4 insertions(+)

diff --git a/src/dataplane/ofproto/ofcache.c b/src/dataplane/ofproto/ofcache.c
index 23d1e4a..2951a4e 100644
--- a/src/dataplane/ofproto/ofcache.c
+++ b/src/dataplane/ofproto/ofcache.c
@@ -420,6 +420,10 @@ void
 clear_all_cache(struct flowcache *cache) {
   int bank;

+  if (cache == NULL) {
+    /* flowcache is not running, nothing to do. */
+    return;
+  }
   for (bank = 0; bank < NBANK; bank++) {
     clear_all_cache_bank(cache->bank[bank]);
   }
```

This fix will be included to next release (v0.2.3 may be available end of Dec 2015) .

Thanks!

**Comment by ynkjm** [comment]
Hi @ashalimov,

DId you test our code in your environment?
If you are OK, we will close this issue.

Thanks,
Yoshi

**Comment by ashalimov** [comment]
Yes, It works. Thanks, Yoshi.
