### ISSUE TITLE
running lagopus -v on tag v0.2.3 will show 0.2.2 not 0.2.3

### ISSUE THREAD

**Issue by ebiken** [lagopus/lagopus#64]
Patch version should be identical to the number on the tag. (3 for this case) 
lagopus_version.h : #define LAGOPUS_VERSION_PATCH 2

$ lagopus -v
Lagopus version 0.2.2-release
[Wed Feb 03 16:48:01 JST 2016][WARN ][1171:0x00007fb1a6a96740:lagopus]:./module.c:201:s_atexit_handler: Module finaliations seems not completed.

**Comment by ynkjm** [comment]
Thank you for this report.

I will fix it.

Thanks again!

**Comment by ynkjm** [comment]
We found critical performance bottleneck in Lagopus 0.2.3, so we have released Lagopus 0.2.4.
We fixed the version number in Lagopus 0.2.4.

Is it OK to close your issue?

Thanks

**Comment by ebiken** [comment]
Sure. thanks for the fix!!

**Comment by ebiken** [comment]
Confirmed on 0.2.4
```
ebiken@lagopus:~/lagopus-0.2.4$ sudo lagopus
ebiken@lagopus:~/lagopus-0.2.4$ lagosh
Lagosh> show version
{
    "product-name": "Lagopus",
    "version": "0.2.4-release"
}
```
