### ISSUE TITLE
How to completely uninstall lagopus 

### ISSUE THREAD

**Issue by Hong-Panha** [lagopus/lagopus#93]
Hi everyone,

I would like to uninstall my Lagopus but i couldn't find the way to do it. Could you please show me how to do it ?

Thanks

**Comment by ynkjm** [comment]
Hi @Hong-Panha 

Currently, we don't provide a script to perform lagopus uninstall.
Could you execute the following commands?

```
$ sudo rm /usr/local/sbin/{lagopus,lagosh}
$ sudo rm /usr/local/lib/liblagopus_*
$ sudo rm -r /usr/local/lib/{liblagopus_*,librte_*,libethdev*,libdpdk.so,dpdk-pmd}
$ sudo rm -r /usr/local/share/doc/lagopus 
$ sudo rm /usr/local/include/lagopus_*
```

**Comment by Hong-Panha** [comment]
Hi,

That is really helpful.

Thanks,
