### ISSUE TITLE
lagopus 0.29/dpdk16.07 low throughput

### ISSUE THREAD

**Issue by ThomasDeiss** [lagopus/lagopus#96]
I'm experiencing low throughput (about 0.24Mpps) with lagopus on 10G interfaces (intel xl710). I'm using lagopus 0.29 without changes on a server with a 1.7GHz CPU, 3 cores are used for lagopus. Lagopus is configured with flows that just sends the input on port 1 to port 2 and vice versa, and similarly for in total 8 ports.
I'm using a moonGen as traffic generator on a 2nd server of the same time, generating 2 streams of 3Gbps each, packet size is 512B. This is a packet rate of about 1.5Mpps. I've run the traffic generator for a couple of seconds, generating in total about 77M packets. Thereafter I checked how often the flows in lagopus have been hit: this was just 13M packets. And eventually the amount of packets returned to the server with the traffic generator was just 3M packets, the receive rate was about 0.24Mpps.
I'm using the same DPDK drivers also for the packet generator, when connecting ports of the packet generator directly by a cable, actually the 6Gbps of transmitted traffic are received again.
Are there specific configuration/compile parameters I need to tune to achieve higher throughput?

**Comment by hirokazutakahashi** [comment]
Hi @ThomasDeiss,

Have you tried "gcc-full-opt" make target?

```
$ ./configure
$ make gcc-full-opt
```

It enables some optimization options for gcc.

**Comment by ThomasDeiss** [comment]
Thanks for the hint, really helpful. I was looking before for such options, but could not find them. With using the options the throughput improved considerably to about 1Mpps. Using additional 2 additional cores, explicit assignment of cores as RX, TX, and workers, and setting fifoness to none, the throughput increased to about 1.25Mpps.
If you have further hints on parameters or settings to improve the throughput, please let me know.
Anyway I propose to close this issue.
