### ISSUE TITLE
Lagopus with ryu_firewall.py

### ISSUE THREAD

**Issue by Hong-Panha** [lagopus/lagopus#97]
Hi Everyone,

I am doing an experiment with my mini-server running
         Lagopus 0.2.9
         ryu 4.7 
         DPDK version is 2.2.0

I installed Lagopus 0.2.9 on with Hybrid enable following QUICKSTART.md.
    $ cd lagopus
    $ ./configure --with-dpdk-dir=${RTE_SDK} --enable-hybrid=yes
    $ make
    $ sudo make install

I want to implement the firewall into my network topology by running rest_firewall.py through ryu-manager. But it doesn't work. After running rest_firewall.py on ryu controller, I execute these command:

# Enable firewall on switch dpid=1
$ curl -X PUT http://localhost:8080/firewall/module/enable/0000000000000001

# Install rules for ICMP connectivity.
$ curl -X POST -d '{"nw_src": "10.0.0.1/32", "nw_dst": "10.0.0.2/32", "nw_proto": "ICMP"}' http://localhost:8080/firewall/rules/0000000000000001
$ curl -X POST -d '{"nw_src": "10.0.0.2/32", "nw_dst": "10.0.0.1/32", "nw_proto": "ICMP"}' http://localhost:8080/firewall/rules/0000000000000001

Even though, I already set the rule to allow ping between hosts (10.0.0.1 and 10.0.0.2) , I still cannot ping. Below is the flow entry of the Lagopus:

Lagosh> show flow
[
    {
        "name": "bridge02", 
        "tables": [
            {
                "table": 0, 
                "flows": [
                    {
                        "priority": 65534, 
                        "idle_timeout": 0, 
                        "hard_timeout": 0, 
                        "cookie": 0, 
                        "dl_type": "arp", 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "output": "normal"
                                    }
                                ]
                            }
                        ], 
                        "stats": {
                            "packet_count": 18, 
                            "byte_count": 1080
                        }
                    }, 
                    {
                        "priority": 1, 
                        "idle_timeout": 0, 
                        "hard_timeout": 0, 
                        "cookie": 1, 
                        "dl_type": "ip", 
                        "nw_proto": 1, 
                        "nw_src": "10.0.0.1/255.255.255.255", 
                        "nw_dst": "10.0.0.2/255.255.255.255", 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "output": "normal"
                                    }
                                ]
                            }
                        ], 
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }
                    }, 
                    {
                        "priority": 1, 
                        "idle_timeout": 0, 
                        "hard_timeout": 0, 
                        "cookie": 2, 
                        "dl_type": "ip", 
                        "nw_proto": 1, 
                        "nw_src": "10.0.0.2/255.255.255.255", 
                        "nw_dst": "10.0.0.1/255.255.255.255", 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "output": "normal"
                                    }
                                ]
                            }
                        ], 
                        "stats": {
                            "packet_count": 0, 
                            "byte_count": 0
                        }
                    }, 
                    {
                        "priority": 0, 
                        "idle_timeout": 0, 
                        "hard_timeout": 0, 
                        "cookie": 0, 
                        "actions": [
                            {
                                "apply_actions": [
                                    {
                                        "output": "controller"
                                    }
                                ]
                            }
                        ], 
                        "stats": {
                            "packet_count": 417, 
                            "byte_count": 82929
                        }
                    }
                ]
            }
        ], 
        "is-enabled": true
    }
]

#And I config my lagopus as below: 

Configure# show lagopus.conf
log {
	syslog;
	ident lagopus;
	debuglevel 1;
	packetdump "";
}
datastore {
	addr 0.0.0.0;
	port 12345;
	protocol tcp;
	tls false;
}
agent {
	channelq-size 1000;
	channelq-max-batches 1000;
}
tls {
	cert-file /usr/local/etc/lagopus/catls.pem;
	private-key /usr/local/etc/lagopus/key.pem;
	certificate-store /usr/local/etc/lagopus;
	trust-point-conf /usr/local/etc/lagopus/check.conf;
}
snmp {
	master-agentx-socket tcp:localhost:705;
	ping-interval-second 10;
}
interface {
	interface01 {
		type ethernet-dpdk-phy;
		port-number 0;
		mtu 1500;
		ip-addr 127.0.0.1;
	}
	interface02 {
		type ethernet-dpdk-phy;
		port-number 1;
		mtu 1500;
		ip-addr 127.0.0.1;
	}
	interface03 {
		type ethernet-dpdk-phy;
		port-number 2;
		mtu 1500;
		ip-addr 127.0.0.1;
	}
}
port {
	port01 {
		interface interface01;
	}
	port02 {
		interface interface02;
	}
	port03 {
		interface interface03;
	}
}
channel {
	channel02 {
		dst-addr 127.0.0.1;
		dst-port 6633;
		local-addr 0.0.0.0;
		local-port 0;
		protocol tcp;
	}
}
controller {
	controller02 {
		channel channel02;
		role equal;
		connection-type main;
	}
}
bridge {
	bridge02 {
		dpid 1;
		controller controller02;
		port port01 1;
		port port02 2;
		port port03 3;
		fail-mode secure;
		flow-statistics true;
		group-statistics true;
		port-statistics true;
		queue-statistics true;
		table-statistics true;
		reassemble-ip-fragments false;
		max-buffered-packets 65535;
		max-ports 225;
		max-tables 225;
		max-flows 4294967295;
		packet-inq-size 1000;
		packet-inq-max-batches 1000;
		up-streamq-size 1000;
		up-streamq-max-batches 1000;
		down-streamq-size 1000;
		down-streamq-max-batches 1000;
		block-looping-ports false;
	}
}

But if I use Open vSwitch, it works just fine. I use the command below to create the network topology.
     $ sudo mn --topo single,3 --mac --switch ovsk --controller remote -x
     $ sudo ovs-vsctl set Bridge s1 protocols=OpenFlow13

After I set the rule above just like Lagopus experiment, I am able to ping between hosts. 
So my question is:
  Why rest_firewall.py dose not work with Lagopus ?
   How to make rest_firewall.py works with Lagopus ?
 
If you need more information related to the experiment, please do let me know.

Regards,
Hong Panha

**Comment by hibitomo** [comment]
Hi @Hong-Panha ,

I tried to run ryu_firewall.py on Lagopus switch and It has worked.
- Lagopus 0.2.9
- ryu 4.8.1
- DPDK 16.07

I installed Lagopus 0.2.9 as fallows:
```
$ cd lagopus
$ ./configure --enable-hybrid
$ make gcc-full-opt
$ sudo make install
```

In the configure, you don't need `--with-dpdk-dir` option.
DPDK is cloned and compiled in `lagopus/src/dpdk` by default.

And, could you show us your running configuration with `Configure# show` command?
Please check that `l2 bridge` is `true` in the bridge configration .
// `Configure# show lagopus.conf` shows your temporal config file.

hibitomo

**Comment by Hong-Panha** [comment]
Hi @hibitomo ,

Thanks for your response.

I will reinstall my Lagopus 0.2.9 without `--with-dpdk-dir`.
As you have mentioned above, In your environment you are running DPDK 16.04 and Ryu 4.8.1. 
Do I have  and update my DPDK to 16.07 to make ryu_firewall.py work on Lagopus ?

If this is the case, Could you tell me the safe way to get my DPDK updated ? Like how to remove the previous version.

Best Regards,
Hong Panha

**Comment by hibitomo** [comment]
Sorry, It is typo. I used DPDK 16.07.

**Comment by hibitomo** [comment]
Hi @Hong-Panha 

I tred the DPDK 16.07. It is the default of Lagopus 0.2.9.
Commit id of Lagopus is `cedca49e109bb99d0e1cf70f5d796c137088ded0`

**Comment by Hong-Panha** [comment]
Hi @hibitomo ,

I am sorry but I don't really understand what you have mentioned above about the commit id of Lagopus. Could you make it more simple ?

As now I have DPDK 2.2 on my environment so what can i do to remove it and get the DPDK 16.07.

Best Regards,
Hong Panha

**Comment by hibitomo** [comment]
Hi @Hong-Panha 

Sorry, I understand your question now.

You can remove the DPDK2.2 module as follows.
```
$ sudo rmmod igb_uio.ko
$ sudo rmmod rte_kni.ko
```

When you configured the lagopus, you got and compiled the DPDK 16.07 in `lagopus/src/dpdk` directory.
For setup of DPDK16.07, please check the [QUICKSTART.md](https://github.com/lagopus/lagopus/blob/release-0.2.9/QUICKSTART.md#environmental-setup) .

**Comment by Hong-Panha** [comment]
Hi @hibitomo ,

Thanks again for your fast response.

I will let you know again if everything works.

Best Regards,
Hong Panha
