### ISSUE TITLE
group table sends to ingress port

### ISSUE THREAD

**Issue by ThomasDeiss** [lagopus/lagopus#98]
I've used a group table to implement port mirroring among 2 ports:
~/ofctl_script/add_flow -t group '{"type":"ALL","group_id":8,"buckets":[{"actions":["OUTPUT:1"]},{"actions":["OUTPUT:2"]},{"actions":["OUTPUT:3"]}]}'

~/ofctl_script/add_flow '{"table_id":0,"priority":10,"actions":["GROUP:8"],"match":{"in_port":1}}'
~/ofctl_script/add_flow '{"table_id":0,"priority":10,"actions":["GROUP:8"],"match":{"in_port":2}}'

When sending a packet to port 1, it actually appears on all 3 ports again. But according to the openflow definition the clone where the egress port corresponds to the ingress port should be discarded. See OF1.3.2, section 5.6.1: 
_Required: all: Execute all buckets in the group. This group is used for multicast or broadcast
forwarding. The packet is effectively cloned for each bucket; one packet is processed for each
bucket of the group. If a bucket directs a packet explicitly out the ingress port, this packet clone
is dropped._

Do I miss something?

**Comment by ynkjm** [comment]
Hi @ThomasDeiss,

Thank you for report.
Your understanding of "all" instruction in group types in OpenFlow 1.3.2 spec is correct.

we will fix this issue on the 0.2.11 version.
When we  fix this bug, let you know.

Thanks!

**Comment by ThomasDeiss** [comment]
Hello @ynkjm ,

thanks for taking care. For the time being I can work around this issue, fine for me if this gets fixed in 0.2.11.

best regards

Thomas

**Comment by ynkjm** [comment]
Hi @ThomasDeiss 

@iMasaruOki has fixed this issue by #102.
Would you test latest commit on your environment?

Thanks
Yoshi

**Comment by ThomasDeiss** [comment]
Hello,

I've currently problems with my environment. I'll test as soon as possible.

best regards
Thomas

**Comment by ThomasDeiss** [comment]
Hello,
I've tested the fix in the small example above as well as in a more complex configuration. In both setups the frames show up on the expected ports and only on those. So, it is working according to openflow spec.
Thanks for the correction.
Sorry for the delay in testing, it took longer than expected to get our test environment working again.

**Comment by ynkjm** [comment]
Hi @ThomasDeiss 

Thank you for report ;)
